
export const THEMED_TUTORIALS = [
    {
      name: "🎵 Basics: Happy Beat",
      icon: "🎵",
      desc: "Learn the FUNDAMENTALS - kick, snare, hi-hat, bass. Perfect for beginners!",
      theme: "from-yellow-400 to-orange-500",
      borderColor: "border-orange-600",
      scenarioIndex: 0,
      difficulty: "Beginner",
      concepts: ["Four-on-the-floor", "Backbeat", "Eighth notes"],
    },
    {
      name: "🌙 Lo-Fi & Chill",
      icon: "🌙",
      desc: "Master the art of SPACE and GROOVE. Less is more!",
      theme: "from-slate-500 to-indigo-600",
      borderColor: "border-indigo-700",
      scenarioIndex: 1,
      difficulty: "Beginner",
      concepts: ["Swing feel", "Sparse patterns", "Chord pads"],
    },
    {
      name: "🏠 House Music 101",
      icon: "💿",
      desc: "The classic FOUR-ON-THE-FLOOR and offbeat hi-hats!",
      theme: "from-pink-500 to-purple-600",
      borderColor: "border-purple-700",
      scenarioIndex: 2,
      difficulty: "Beginner",
      concepts: ["Four-on-the-floor", "Offbeat hi-hats", "Synth stabs"],
    },
    {
      name: "🌍 World: Afrobeat",
      icon: "🪘",
      desc: "Learn POLYRHYTHM - multiple rhythms playing together!",
      theme: "from-orange-500 to-red-600",
      borderColor: "border-red-700",
      scenarioIndex: 3,
      difficulty: "Intermediate",
      concepts: ["Syncopation", "Polyrhythm", "World rhythms"],
    },
    {
      name: "🚀 Drum & Bass",
      icon: "⚡",
      desc: "Fast, intense, rolling breaks and heavy bass!",
      theme: "from-indigo-500 to-violet-600",
      borderColor: "border-violet-700",
      scenarioIndex: 4,
      difficulty: "Intermediate",
      concepts: ["Two-step pattern", "Snare rolls", "Rolling bass"],
    },
    {
      name: "👑 Trap Beats",
      icon: "🔥",
      desc: "Hi-hat rolls, heavy 808s, and that BOUNCE!",
      theme: "from-red-600 to-red-900",
      borderColor: "border-red-800",
      scenarioIndex: 5,
      difficulty: "Intermediate",
      concepts: ["Hi-hat rolls", "808 bass", "Sparse kicks"],
    },
    {
      name: "🔥 Reggaeton Dembow",
      icon: "💿",
      desc: "The DEMBOW rhythm that powers Latin hits!",
      theme: "from-yellow-500 to-orange-600",
      borderColor: "border-orange-700",
      scenarioIndex: 6,
      difficulty: "Intermediate",
      concepts: ["Dembow pattern", "Latin rhythm", "Dance groove"],
    },
    {
      name: "🎤 Hip Hop Boom Bap",
      icon: "🎧",
      desc: "Classic hip hop - BOOM (kick) BAP (snare)!",
      theme: "from-amber-600 to-stone-700",
      borderColor: "border-stone-700",
      scenarioIndex: 7,
      difficulty: "Beginner",
      concepts: ["Boom bap", "Swing", "Head-nodding groove"],
    },
    {
      name: "🎸 Rock Drumming",
      icon: "🤘",
      desc: "Simple, powerful, driving ROCK beat!",
      theme: "from-gray-600 to-red-800",
      borderColor: "border-red-900",
      scenarioIndex: 8,
      difficulty: "Beginner",
      concepts: ["Backbeat", "Tom fills", "Steady rhythm"],
    },
    {
      name: "🤖 Techno Hypnosis",
      icon: "🔊",
      desc: "Minimal, hypnotic, REPETITIVE trance state!",
      theme: "from-cyan-500 to-gray-800",
      borderColor: "border-gray-800",
      scenarioIndex: 9,
      difficulty: "Intermediate",
      concepts: ["Minimalism", "Repetition", "Trance rhythm"],
    },
  ];
